AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  AppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: functions/app.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable
      Architectures:
      - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: helloWorld
          POWERTOOLS_METRICS_NAMESPACE: sam-app
          IDEMPOTENCY_TABLE: !Ref IdempotencyTable
          LOG_LEVEL: INFO
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - functions/app.ts
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IdempotencyTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sam-app/parameter
      Type: String
      Value: "42"

  TraceParameterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: tracer.handler
      Runtime: nodejs20.x
      MemorySize: 1024
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref Parameter
      Architectures:
      - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: tracingParameters
          POWERTOOLS_METRICS_NAMESPACE: sam-app
          LOG_LEVEL: INFO
          PARAMETER_NAME: !Ref Parameter
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - tracing.ts

